---
#- hosts: esxi
- hosts: cluster-1
  become: yes
  become_user: root
  gather_facts: false
  tasks:
  - name: Print variable names
    debug:
      msg: "How are you Kanul {{ ansible_host }}"

  - name: Print Group variable names
    debug:
      msg: "{{ description }} from {{ commonvar }}"

  - name: Print Host variable names
    debug:
      msg: "vmk0_address = {{ vmk0_address }} and vmk1_address={{ vmk1_address }}"
